version: '3'

services:
  mail-services:
    container_name: mail-services
    restart: unless-stopped
    image: livecom-mail-server
    env_file:
      - .env
    ports:
      - "25:25" 
      - "110:110" 
      - "143:143" 
      - "465:465" 
      - "993:993" 
      - "995:995" 
      - "8092:8092" 
      - "2425:2425"
    volumes:
      - ./files/etc:/etc/
      - ./files/usr:/usr/
    networks:
      - mail

  postfixadmin:
    container_name: admin-mail-server
    image: postfixadmin
    depends_on:
      - "mail-services"
    restart: unless-stopped
    ports: 
      - "8090:80"
    environment:
      - POSTFIXADMIN_DB_TYPE=mysqli
      - POSTFIXADMIN_DB_HOST=${POSTFIXADMIN_DB_HOST}
      - POSTFIXADMIN_DB_USER=${POSTFIXADMIN_DB_USER}
      - POSTFIXADMIN_DB_NAME=${POSTFIXADMIN_DB_NAME}
      - POSTFIXADMIN_DB_PASSWORD=${POSTFIXADMIN_DB_PASSWORD}
    networks:
      - mail

  roundcube:
    container_name: webmail-mail-server
    image: roundcube/roundcubemail:latest
    depends_on:
      - "mail-services"
    restart: unless-stopped
    ports: 
      - "8091:80"
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=${ROUNDCUBEMAIL_DB_HOST}
      - ROUNDCUBEMAIL_DB_PASSWORD=${ROUNDCUBEMAIL_DB_PASSWORD}
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=${ROUNDCUBEMAIL_DEFAULT_HOST}
      - ROUNDCUBEMAIL_SMTP_SERVER=${ROUNDCUBEMAIL_SMTP_SERVER}
    networks:
      - mail

networks:
  mail:
    internal: true